#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

echo "Starting app..."
npm run dev &

APP_PID=$!

echo "Waiting for app to be ready..."
npx wait-on http://localhost:5173

echo "Running E2E tests before push..."
npm run cy:run

TEST_RESULT=$?

echo "Stopping app..."
kill $APP_PID

exit $TEST_RESULT